name: ares_builder
description: Ares Builder - Otonom APK Derleyici
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  archive: ^3.6.1
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/main_screen_bg.png
    - assets/images/settings_dialog_bg.png
